name: shelf_modular
description: Smart project structure with dependency injection and route management
version: 1.0.0
homepage: https://github.com/Flutterando/modular

environment:
  sdk: ">=2.12.0 <3.0.0"

dependencies:
  args: ^2.2.0
  shelf: ^1.1.0
  meta: ">=1.3.0 <2.0.0"
  modular_core:
    path: ../modular_core
  mime: ^1.0.0
  http_parser: ^4.0.0
  web_socket_channel: ^2.1.0
  shelf_web_socket: ^1.0.1

dev_dependencies:
  mocktail: ^0.1.4
  pedantic: ^1.10.0
  test: ^1.17.12
