name: flutter_modular
description: Smart project structure with dependency injection and route management
version: 4.2.0
homepage: https://github.com/Flutterando/modular

environment:
  sdk: ">=2.12.0 <3.0.0"

dependencies:
  flutter_modular_annotations:
    path: ../flutter_modular_annotations
  triple: ">=1.3.0+2 <2.0.0"
  modular_core:
    path: ../modular_core
  meta: ">=1.3.0 <2.0.0"
  flutter:
    sdk: flutter

dev_dependencies:
  pedantic: ^1.10.0
  mocktail: ^0.1.4
  flutter_test:
    sdk: flutter

flutter:
